apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: getting-started
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.openshift.io/runtime: quarkus
  name: getting-started
  namespace: quarkus
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: getting-started
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  sessionAffinity: None
  type: ClusterIP
